travis:
  secure:
    BINSTAR_TOKEN: j1QAd9ImHTQWbRcL00YC+dKDiAsR8eUWi1F0JasCp2d5Mx71t8XvAMXNzjeP8fY/kBUop/nB+iWopzGZenr7SWD8jNM/jqYVDqeaujQ80MIYF0q6wne6aS8IhCXo9h/IiKOxYY14RpzQemlab4B0a1H7J8+kT8KKe+mL4saizMlMAaIsVMh0GIUQrsZfE4+971TJKHPOGhUqoug9D149cacp1aJze2SYTfWew9rym/dK9yXZVvHx4t9pQ+Ghy9KRZ7rOh3yG+NVLDzVYmXe1wq9fcRkvjJdmiWSwMJOcobUtEcPlxxb2AOvjb5NVCsgQkf0WXn3cwjgdTH7RGQpZhKyVfPeoYzB5YO2Vs1fnUGvSA2scPyks5RzmOHwLhpjcuBhXGPJ/exuZJ1pzzlqH8c7ZZIx4XlPXeQ2I/t1YezWcXUD3F9AkNy+dYA6l5IRGEo4JXB68j1nZBOMZh3Jje93c0cdRd5fZRRY4i2Tzdf8JKoz0yCRy/OkPFubAnH5G2ir8g7bB4ETm1cpbmL8sMpxctVhmsN6wqXu+4j6O1io3bESTQpGGvKeIipM+0ot47dunL3M3Ow3SfFWKfavAvztcCIz9L2Xpm9Zv1egPXh1l5MjVPEftwosS9j60PI+zKll21zDIgqIMK7D30u6HT62kYxvT0wl/CqqP1+FJ7F0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
